<?php /* @var $this HackathonWebsite_ProjectIdea_Block_Form */ ?>
<div class="projectIdea-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create a project idea') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('*/*/post') ?>" method="post" id="form-validate">

        <input type="text" name="title" />
        <input type="text" name="submitter" />
        <textarea name="description"></textarea>
        <input type="submit" />

    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        //]]>
    </script>
</div>
