<?php /* @var $this HackathonWebsite_ProjectIdea_Block_List */ ?>
<div class="page-title">
    <h1>
        <?php echo $this->__('Ideas for Projects') ?>
    </h1>
    <button class="btn btn-primary" onclick="setLocation('<?php echo $this->getUrl('projectIdea/index/add') ?>')"><?php echo $this->__('Add an Idea') ?></button>
</div>

<?php if ($this->getProjectIdeaCollection()->getSize()): ?>
    <ul id="projectIdea-list" class="unstyled">
        <?php foreach ($this->getProjectIdeaCollection() as $idea): ?>
            <li class="well">
                <strong><?php echo $this->htmlEscape($idea->getTitle()); ?></strong> (<?php echo $this->htmlEscape($idea->getSubmitter());?>)
                <p><?php echo $this->htmlEscape($idea->getDescription()); ?></p>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else : ?>
    <div class="alert fade in">
        <a class="close" data-dismiss="alert">×</a>
        <?php echo $this->__('There are currently no project ideas.') ?>
    </div>
<?php endif; ?>

<button class="btn btn-primary" onclick="setLocation('<?php echo $this->getUrl('projectIdea/index/add') ?>')"><?php echo $this->__('Add an Idea') ?></button>
